image: python:3.9
stages:
  - format
  - test

### =============================================================
### ==============     FORMATTING STAGE    ======================
### =============================================================

run formatters: # Check whether code adheres to the required formats
  stage: format
  script:
    - pip install pre-commit && pre-commit install
    - pre-commit run -a
  retry: 0
  tags:
    - deep-thought

### =============================================================
### ==============     TESTING STAGE    =========================
### =============================================================
run tests: # Run tests
  stage: test
  parallel:
    matrix:
      - IMAGE: ["python:3.8", "python:3.9", "python:3.10"]
  image: $IMAGE
  before_script:
    # apt install
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y cmake wget
    # acados install
    - cd $CI_PROJECT_DIR && git submodule update --recursive --init || exit 1
    - mkdir -p $CI_PROJECT_DIR/external/acados/build && cd $CI_PROJECT_DIR/external/acados/build && cmake -DACADOS_PYTHON=ON .. && make install -j4 && export ACADOS_SOURCE_DIR=$CI_PROJECT_DIR/external/acados && export LD_LIBRARY_PATH=$ACADOS_SOURCE_DIR/lib || exit 1
    - cd $CI_PROJECT_DIR/external/acados/bin && wget https://github.com/acados/tera_renderer/releases/download/v0.0.34/t_renderer-v0.0.34-linux -O t_renderer && chmod +x t_renderer || exit 1
    - cd $CI_PROJECT_DIR && python -m venv .venv
    - cd $CI_PROJECT_DIR && source .venv/bin/activate && pip install -r requirements.txt || exit 1
    - cd $CI_PROJECT_DIR || exit 1
  script:
    - cd $CI_PROJECT_DIR && source .venv/bin/activate && pip install pytest
    - cd $CI_PROJECT_DIR && source .venv/bin/activate && pytest --ignore external/
  retry: 0
  tags:
    - deep-thought
