#!/bin/bash
ACADOS_NUM_THREADS=$1
ACADOS_PYTHON=ON
ACADOS_WITH_OPENMP=${2:-ON}

mkdir -p $ACADOS_SOURCE_DIR/build
cd $ACADOS_SOURCE_DIR/build

cmake -DACADOS_PYTHON=$ACADOS_PYTHON -DACADOS_WITH_OPENMP=$ACADOS_WITH_OPENMP -DACADOS_NUM_THREADS=$ACADOS_NUM_THREADS ..
make install -j4
